version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - 3010:3010
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 3011:3011
    working_dir: /app-backend
    command: npm run dev
    volumes: 
      - ./backend/src:/app-backend/src
    environment:
      - APP_PORT=3011
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=3306
  db:
    image: postgres
    container_name: db
    ports:
      - 3012:5432
    environment:
      - POSTGRES_ROOT_PASSWORD=123456
    restart: 'always'
