version: '3.9'
services:
  frontend:
    container_name: app_radarfit
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]  
      timeout: 10s
      retries: 5
  backend:
    container_name: api_radarfit
    build: ./backend
    ports:
      - 3011:3011
    working_dir: /api-backend
    command: npm run dev
    volumes: 
      - ./backend/src:/app-backend/src
    environment:
      - APP_PORT=3001
      - DB_USER=postgres
      - DB_PASS=123456
      - DB_HOST=localhost
      - DB_PORT=5432
    depends_on:
      db:  
        condition: service_healthy  
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]  
      timeout: 10s
      retries: 5
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 10s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=123456
    restart: 'always'
